//var config='{"name":"decoration","background_music":"games/decoration/res/background.mp3","sound_intro":"","images":[{"res":"games/decoration/res/image.png","scale":"1.1","rotate1":"20","opacity":"220","sound_click":"games/decoration/res/black.mp3","animation_click":"","animation_idle":"","animation_start":"","animation_end":"fade_out","x":800,"y":500},{"res":"games/decoration/res/image.png","scale":"1.1","rotate1":"20","opacity":"220","sound_click":"games/decoration/res/black.mp3","animation_click":"","animation_idle":"","animation_start":"","animation_end":"fade_out","x":1000,"y":500}],"backgrounder":{"res":"games/decoration/res/background.jpg","scale":0.416,"opacity":220,"x":568,"y":320},"item1":[{"res":"games/decoration/res/item1.png","scale":"0.55","rotate1":"0","opacity":220,"sound_click":"games/decoration/res/black.mp3","animation_click":"","animation_idle":"","animation_start":"","animation_end":"fade_out"},{"res":"games/decoration/res/item2.png","scale":"0.15","rotate1":"0","opacity":220,"sound_click":"games/decoration/res/black.mp3","animation_click":"","animation_idle":"","animation_start":"","animation_end":"fade_out"},{"res":"games/decoration/res/item3.png","scale":"0.15","rotate1":"0","opacity":220,"sound_click":"games/decoration/res/black.mp3","animation_click":"","animation_idle":"","animation_start":"","animation_end":"fade_out"},{"res":"games/decoration/res/item4.png","scale":"0.55","rotate1":"0","opacity":220,"sound_click":"games/decoration/res/black.mp3","animation_click":"","animation_idle":"","animation_start":"","animation_end":"fade_out"},{"res":"games/decoration/res/item5.png","scale":"0.65","rotate1":"0","opacity":220,"sound_click":"games/decoration/res/black.mp3","animation_click":"","animation_idle":"","animation_start":"","animation_end":"fade_out"}],"category":[{"target":[0,1],"untarget":[2,3,4],"res":"games/decoration/res/category1.png","scale":"0.42","rotate1":"10","opacity":220,"sound_click":"games/decoration/res/black.mp3","animation_click":"","animation_idle":"","animation_start":"","animation_end":"fade_out"},{"target":[0,1,2],"untarget":[3,4],"res":"games/decoration/res/category2.png","scale":"0.7","rotate1":"10","opacity":220,"sound_click":"games/decoration/res/black.mp3","animation_click":"","animation_idle":"","animation_start":"","animation_end":"fade_out"},{"target":[0,1,2,3,4],"untarget":[],"res":"games/decoration/res/category3.png","scale":"0.7","rotate1":"10","opacity":220,"sound_click":"games/decoration/res/black.mp3","animation_click":"","animation_idle":"","animation_start":"","animation_end":"fade_out"}],"smart_object":{"x":600,"y":320,"res":"games/decoration/res/smartobj.png","scale":"0.42","rotate1":"0","opacity":220,"sound_click":"games/decoration/res/black.mp3","animation_click":"elastic_scale_in","animation_idle":"","animation_start":"","animation_end":"fade_out"}}'
var config_decoration={
    "name":"decoration",
    "background_music":"games/decoration/res/background.mp3",
    "sound_intro":"",
    "images":[
        {
            "res":"games/decoration/res/image.png",
            "scale":"1.1",
            "rotate1":"20",
            "opacity":"220",
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out",
            "x":800,
            "y":500
        },
        {
            "res":"games/decoration/res/image.png",
            "scale":"1.1",
            "rotate1":"20",
            "opacity":"220",
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out",
            "x":1000,
            "y":500
        }
    ],
    "backgrounder":{
        "res":"games/decoration/res/background.jpg",
        "scale":0.416,
        "opacity":220,
        "x":568,
        "y":320,

    },

    "item1":[
        {
            "res":"games/decoration/res/item1.png",
            "scale":"0.55",
            "rotate1":"0",
            "opacity":220,
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out"
        },
        {
            "res":"games/decoration/res/item2.png",
            "scale":"0.15",
            "rotate1":"0",
            "opacity":220,
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out"
        },
        {
            "res":"games/decoration/res/item3.png",
            "scale":"0.15",
            "rotate1":"0",
            "opacity":220,
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out"
        },
        {
            "res":"games/decoration/res/item4.png",
            "scale":"0.55",
            "rotate1":"0",
            "opacity":220,
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out"
        },
        {
            "res":"games/decoration/res/item5.png",
            "scale":"0.65",
            "rotate1":"0",
            "opacity":220,
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out"
        }
    ],
    "category":[
        {
            "target":[0,1],
            "untarget":[2,3,4],
            "res":"games/decoration/res/category1.png",
            "scale":"0.42",
            "rotate1":"10",
            "opacity":220,
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out"
        },
        {
            "target":[0,1,2],
            "untarget":[3,4],
            "res":"games/decoration/res/category2.png",
            "scale":"0.7",
            "rotate1":"10",
            "opacity":220,
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out"
        },
        {
            "target":[0,1,2,3,4],
            "untarget":[],
            "res":"games/decoration/res/category3.png",
            "scale":"0.7",
            "rotate1":"10",
            "opacity":220,
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out"
        }
    ],
    "smart_object":
        {
            "x":600,
            "y":320,
            "res":"games/decoration/res/smartobj.png",
            "scale":"0.42",
            "rotate1":"0",
            "opacity":220,
            "sound_click":"games/decoration/res/black.mp3",
            "animation_click":"elastic_scale_in",
            "animation_idle":"",
            "animation_start":"",
            "animation_end":"fade_out"
        }

};
var move_h_decoration=eval(config_decoration);
